create table AUTHORITIES (id int4 not null, FK_AUTHORITY int4, FK_IDENTITY int4, FK_RESOURCE int4, primary key (id));
create table AUTHORITIES_INFO (id int4 not null, FK_AUTHORITIES int4, FK_AUTHORITIES_INFO int4, DESCRIPTION varchar(4000), INFO int4, primary key (id));
create table AUTHORITY (id int4 not null, DESCRIPTION varchar(255), INFO_GET_URL varchar(4000), INFO_LIST_URL varchar(4000), PRIORITY int4, USE_INFOS boolean, primary key (id));
create table CONFIGURATION (id int4 not null, DESCRIPTION varchar(4000) not null, DISCRIMINATOR varchar(255) not null, END_DATE timestamp, KEY varchar(4000) not null, PRIORITY int4, START_DATE timestamp, VALUE varchar(4000) not null, primary key (id));
create table CONFIGURATION_DATA (FK_CONFIGURATION int4 not null, DISCRIMINATOR varchar(255) not null, FK_BLOB_VALUE varchar(255), BOOLEAN_VALUE boolean, CLOB_VALUE text, FK_CONFIGURATION_VALUE int4, DATE_VALUE timestamp, INTEGER_VALUE int4, NUMBER_VALUE numeric(18, 3), STRING_VALUE varchar(4000), primary key (FK_CONFIGURATION, DISCRIMINATOR));
create table CONFIGURATION_LINK (id int4 not null, FK_CHILD int4, DISCRIMINATOR varchar(255), FK_PARENT int4, PRIORITY int4, primary key (id));
create table I18N (id int4 not null, CONTEXT varchar(255), KEY varchar(1000), VALUE varchar(4000), primary key (id));
create table I18N_DATA (DISCRIMINATOR varchar(255) not null, FK_I18N int4 not null, STRING_VALUE varchar(4000), primary key (FK_I18N, DISCRIMINATOR));
create table IDENTITY (id int4 not null, FK_TEAM int4, FK_USER int4, primary key (id));
create table RESOURCE_GA (id int4 not null, ALLOWED boolean, DATA_ACCESS_LOGIC varchar(255), DESCRIPTION varchar(4000), DISCRIMINATOR varchar(255), IDENTIFIER varchar(4000), NOTE varchar(4000), primary key (id));
create table RESOURCE_GA_LINK (FK_CHILD int4 not null, FK_PARENT int4 not null, ALLOWED boolean, primary key (FK_CHILD, FK_PARENT));
create table SEARCH_BUILDER (id int4 not null, FILTER_CLAUSE varchar(4000), GROUP_CLAUSE varchar(4000), NAME varchar(4000), ORDER_CLAUSE varchar(4000), PAGE_SIZE int4, SELECT_CLAUSE varchar(4000), STRATEGY varchar(255), URL varchar(1000), VALIDATION_CLAUSE varchar(4000), WEB_VIEW varchar(255), WITH_CLAUSE varchar(4000), primary key (id));
create table SEARCH_BUILDER_PARAMETER (id int4 not null, NAME varchar(255), FK_SEARCH_BUILDER int4, VALUE varchar(4000), primary key (id));
create table SEARCH_BUILDER_WIDGET_LINK (id int4 not null, ORDERING int4, FK_SEARCH_BUILDER int4, FK_WIDGET int4, primary key (id));
create table TREE_NODE (id int4 not null, ATTACCHED_RESOURCE varchar(4000), BROTHER_ORDER int4, CSS_CLASS text, DEFAULT_PARAMETER text, ICON text, IDENTIFIER varchar(4000) not null, LINK varchar(4000), ONCLICK text, ONMOUSEOVER text, SHOW_PARENT_NAME boolean, FK_TREE_NODE_PARENT int4, FK_TREE_NODE_TYPE int4, VISIBILITY_PATH text, VISIBILITY_RULE text, primary key (id));
create table TREE_NODE_DICTIONARY (id int4 not null, DISCRIMINATOR varchar(255), I18N_CUSTOM_IDENTIFIER varchar(4000), FK_TREE_NODE int4 not null, primary key (id));
create table TREE_NODE_TYPE (id int4 not null, BEAN_SERVICE_NAME varchar(255), DESCRIPTION varchar(255) not null, ICON varchar(255) not null, IDENTIFIER varchar(4000) not null, METHOD_NAME varchar(255), MODEL_CLASS varchar(255), VALID_CHILDREN varchar(255) not null, VIEW_NAME varchar(255), primary key (id));
create table VIEW_BUILDER (id int4 not null, ALTERNATIVE_IDENTIFIERS varchar(4000), CUSTOM_TITLE_KEY varchar(4000), IDENTIFIER varchar(4000), MANAGED_BY varchar(255), STATE varchar(4000), VERSION_DATE timestamp, VERSION_INFO varchar(255), VIEW_NAME varchar(4000), primary key (id));
create table VIEW_BUILDER_PARAMETER (id int4 not null, NAME varchar(255), VALUE varchar(4000), FK_VIEW_BUILDER int4, primary key (id));
create table VIEW_BUILDER_VALIDATOR (VALIDATOR_TYPE varchar(31) not null, id int4 not null, ORDERING int4, FK_VIEW_BUILDER int4, BEAN_NAME varchar(255), FIELD_NAME varchar(255), VALIDATION_RULES text, CLASS_NAME varchar(255), primary key (id));
create table VIEW_BUILDER_WIDGET_LINK (id int4 not null, LAYOUT_MODE varchar(255), ORDERING int4, FK_VIEW_BUILDER int4, FK_WIDGET int4, primary key (id));
create table WIDGET (DISCRIMINATOR varchar(31) not null, id int4 not null, ATTACCHED_RESOURCE varchar(4000), MODEL_ATTRIBUTE_NAME varchar(4000), NAME varchar(4000), PAGE_ATTRIBUTE_NAME varchar(255), FK_WIDGET int4, SECTION varchar(255), POPULATION_TYPE varchar(255), POPULATION_VALUE varchar(4000), primary key (id));
create table WIDGET_DICTIONARY (id int4 not null, ACTIVATION_DATE date, DEACTIVATION_DATE date, DECORATOR_CLASS varchar(255), DISCRIMINATOR varchar(255), HIDDEN_VALUE varchar(4000), I18N_CUSTOM_IDENTIFIER varchar(4000), ORDERING int4, FK_DICTIONARY int4, STYLE_VALUE varchar(255), FK_WIDGET int4 not null, WITH_CLAUSE varchar(255), primary key (id));
create table WIDGET_LINK (id int4 not null, FK_CHILD int4, ORDERING int4, FK_PARENT int4, primary key (id));
create table WIDGET_PARAMETER (id int4 not null, DISCRIMINATOR varchar(1000), ORDERING int4, VALUE varchar(1000), FK_WIDGET int4, primary key (id));
alter table CONFIGURATION_DATA add constraint UK_p3dd2j9o6k61ky2d53jpgsowh unique (FK_CONFIGURATION_VALUE);
alter table TREE_NODE add constraint UK_efajpbgvwc4kx1lxmcnygrl23 unique (IDENTIFIER);
alter table TREE_NODE_TYPE add constraint UK_mf6kxbiwxb7f0wewifmnvcp0p unique (IDENTIFIER);
alter table AUTHORITIES add constraint FK_2hiekwvkh63suypw2twy1begf foreign key (FK_AUTHORITY) references AUTHORITY;
alter table AUTHORITIES add constraint FK_j8e6xh0qaf39qdnwbeg6poydx foreign key (FK_IDENTITY) references IDENTITY;
alter table AUTHORITIES add constraint FK_aeawwv39ghkjg38ler3apuw8y foreign key (FK_RESOURCE) references RESOURCE_GA;
alter table AUTHORITIES_INFO add constraint FK_17pbbksogqpfq6y8p272vyyvy foreign key (FK_AUTHORITIES) references AUTHORITIES;
alter table AUTHORITIES_INFO add constraint FK_cyj5tvmo34rktn46hld4tw8x8 foreign key (FK_AUTHORITIES_INFO) references AUTHORITIES;
alter table AUTHORITIES_INFO add constraint FK_cyj5tvmo34rktn46hld4tw8x8 foreign key (FK_AUTHORITIES_INFO) references AUTHORITIES_INFO;
alter table CONFIGURATION_DATA add constraint FK_c2au3fg8hx9dsl9gp0vfvtdy foreign key (FK_CONFIGURATION) references CONFIGURATION;
alter table CONFIGURATION_DATA add constraint FK_p3dd2j9o6k61ky2d53jpgsowh foreign key (FK_CONFIGURATION_VALUE) references CONFIGURATION;
alter table CONFIGURATION_LINK add constraint FK_6ocu9oxie3wjfnuxrnocpr8oa foreign key (FK_CHILD) references CONFIGURATION;
alter table CONFIGURATION_LINK add constraint FK_dvoyemamv45ioecyqrxy9sacl foreign key (FK_PARENT) references CONFIGURATION;
alter table I18N_DATA add constraint FK_4bvmtk6yq1wc3vk4aje6j7ntv foreign key (FK_I18N) references I18N;
alter table RESOURCE_GA_LINK add constraint FK_s71dy277ggl662dkbh5gquhol foreign key (FK_CHILD) references RESOURCE_GA;
alter table RESOURCE_GA_LINK add constraint FK_ctc2a2cn86mqtuyroh4ctey0o foreign key (FK_PARENT) references RESOURCE_GA;
alter table SEARCH_BUILDER_PARAMETER add constraint FK_b9nw9p5qvv6b90r80ejk68ej8 foreign key (FK_SEARCH_BUILDER) references SEARCH_BUILDER;
alter table SEARCH_BUILDER_WIDGET_LINK add constraint FK_pgw5oohod4nwrk1gj45ixaxl4 foreign key (FK_SEARCH_BUILDER) references SEARCH_BUILDER;
alter table SEARCH_BUILDER_WIDGET_LINK add constraint FK_b05t6uy4pk5n89p3vw2w2tsjc foreign key (FK_WIDGET) references WIDGET;
alter table TREE_NODE add constraint FK_28fx7qr67i1e18869885kgc4q foreign key (FK_TREE_NODE_PARENT) references TREE_NODE;
alter table TREE_NODE add constraint FK_ohlydp4227pvl9fy430b7ko3u foreign key (FK_TREE_NODE_TYPE) references TREE_NODE_TYPE;
alter table TREE_NODE_DICTIONARY add constraint FK_hbw1waf6fhxosyg3krwg96bym foreign key (FK_TREE_NODE) references TREE_NODE;
alter table VIEW_BUILDER_PARAMETER add constraint FK_l4vh96j0wv1bd97y7648rbbso foreign key (FK_VIEW_BUILDER) references VIEW_BUILDER;
alter table VIEW_BUILDER_VALIDATOR add constraint FK_b4qm4t082qq5xdpnx2l7xcxvi foreign key (FK_VIEW_BUILDER) references VIEW_BUILDER;
alter table VIEW_BUILDER_WIDGET_LINK add constraint FK_9cmyg97fl51la7m6tajc3lfjn foreign key (FK_VIEW_BUILDER) references VIEW_BUILDER;
alter table VIEW_BUILDER_WIDGET_LINK add constraint FK_nlqyjgbf8ucrbpiioqgtuwwv6 foreign key (FK_WIDGET) references WIDGET;
alter table WIDGET add constraint FK_530smuyqgxeyd2xwp86fc0uh1 foreign key (FK_WIDGET) references WIDGET;
alter table WIDGET_DICTIONARY add constraint FK_kkvloaqvdgnbqxcw04xdh9mfy foreign key (FK_DICTIONARY) references WIDGET_DICTIONARY;
alter table WIDGET_DICTIONARY add constraint FK_5ouw34mu4pvsngro5tecbfbrk foreign key (FK_WIDGET) references WIDGET;
alter table WIDGET_LINK add constraint FK_8hilkpgyarn4mwe6v6olv0brn foreign key (FK_CHILD) references WIDGET;
alter table WIDGET_LINK add constraint FK_2dh9nxa6sdjt8xg1iu9ho6pvj foreign key (FK_PARENT) references WIDGET;
alter table WIDGET_PARAMETER add constraint FK_i5vvr94597qrm2p9p5im5qvks foreign key (FK_WIDGET) references WIDGET;
create sequence AUTHORITIES_INFO_SEQ;
create sequence AUTHORITIES_SEQ;
create sequence AUTHORITY_SEQ;
create sequence CONFIGURATION_LINK_SEQ;
create sequence CONFIGURATION_SEQ;
create sequence I18N_SEQ;
create sequence IDENTITY_SEQ;
create sequence RESOURCE_SEQ;
create sequence SEARCH_BUILDER_PARAMETER_SEQ;
create sequence SEARCH_BUILDER_SEQ;
create sequence SEARCH_BUILDER_WIDGET_LINK_SEQ;
create sequence TREE_NODE_DICTIONARY_SEQ;
create sequence TREE_NODE_SEQ;
create sequence TREE_NODE_TYPE_SEQ;
create sequence VIEW_BUILDER_PARAMETER_SEQ;
create sequence VIEW_BUILDER_SEQ;
create sequence VIEW_BUILDER_VALIDATOR_SEQ;
create sequence VIEW_BUILDER_WIDGET_LINK_SEQ;
create sequence WIDGET_DICTIONARY_SEQ;
create sequence WIDGET_LINK_SEQ;
create sequence WIDGET_PARAMETER_SEQ;
create sequence WIDGET_SEQ;
