create table AUTHORITIES (id number(10,0) not null, FK_AUTHORITY number(10,0), FK_IDENTITY number(10,0), FK_RESOURCE number(10,0), primary key (id));
create table AUTHORITIES_INFO (id number(10,0) not null, FK_AUTHORITIES number(10,0), FK_AUTHORITIES_INFO number(10,0), DESCRIPTION varchar2(4000 char), INFO number(10,0), primary key (id));
create table AUTHORITY (id number(10,0) not null, DESCRIPTION varchar2(255 char), INFO_GET_URL varchar2(4000 char), INFO_LIST_URL varchar2(4000 char), PRIORITY number(10,0), USE_INFOS number(1,0), primary key (id));
create table CONFIGURATION (id number(10,0) not null, DESCRIPTION varchar2(4000 char) not null, DISCRIMINATOR varchar2(255 char) not null, END_DATE timestamp, KEY varchar2(4000 char) not null, PRIORITY number(10,0), START_DATE timestamp, VALUE varchar2(4000 char) not null, primary key (id));
create table CONFIGURATION_DATA (FK_CONFIGURATION number(10,0) not null, DISCRIMINATOR varchar2(255 char) not null, FK_BLOB_VALUE varchar2(255 char), BOOLEAN_VALUE number(1,0), CLOB_VALUE clob, FK_CONFIGURATION_VALUE number(10,0), DATE_VALUE timestamp, INTEGER_VALUE number(10,0), NUMBER_VALUE number(18,3), STRING_VALUE varchar2(4000 char), primary key (FK_CONFIGURATION, DISCRIMINATOR));
create table CONFIGURATION_LINK (id number(10,0) not null, FK_CHILD number(10,0), DISCRIMINATOR varchar2(255 char), FK_PARENT number(10,0), PRIORITY number(10,0), primary key (id));
create table I18N (id number(10,0) not null, CONTEXT varchar2(255 char), KEY varchar2(1000 char), VALUE varchar2(4000 char), primary key (id));
create table I18N_DATA (DISCRIMINATOR varchar2(255 char) not null, FK_I18N number(10,0) not null, STRING_VALUE varchar2(4000 char), primary key (FK_I18N, DISCRIMINATOR));
create table IDENTITY (id number(10,0) not null, FK_TEAM number(10,0), FK_USER number(10,0), primary key (id));
create table RESOURCE_GA (id number(10,0) not null, ALLOWED number(1,0), DATA_ACCESS_LOGIC varchar2(255 char), DESCRIPTION varchar2(4000 char), DISCRIMINATOR varchar2(255 char), IDENTIFIER varchar2(4000 char), NOTE varchar2(4000 char), primary key (id));
create table RESOURCE_GA_LINK (FK_CHILD number(10,0) not null, FK_PARENT number(10,0) not null, ALLOWED number(1,0), primary key (FK_CHILD, FK_PARENT));
create table SEARCH_BUILDER (id number(10,0) not null, FILTER_CLAUSE varchar2(4000 char), GROUP_CLAUSE varchar2(4000 char), NAME varchar2(4000 char), ORDER_CLAUSE varchar2(4000 char), PAGE_SIZE number(10,0), SELECT_CLAUSE varchar2(4000 char), STRATEGY varchar2(255 char), URL varchar2(1000 char), VALIDATION_CLAUSE varchar2(4000 char), WEB_VIEW varchar2(255 char), WITH_CLAUSE varchar2(4000 char), primary key (id));
create table SEARCH_BUILDER_PARAMETER (id number(10,0) not null, NAME varchar2(255 char), FK_SEARCH_BUILDER number(10,0), VALUE varchar2(4000 char), primary key (id));
create table SEARCH_BUILDER_WIDGET_LINK (id number(10,0) not null, ORDERING number(10,0), FK_SEARCH_BUILDER number(10,0), FK_WIDGET number(10,0), primary key (id));
create table TREE_NODE (id number(10,0) not null, ATTACCHED_RESOURCE varchar2(4000 char), BROTHER_ORDER number(10,0), CSS_CLASS clob, DEFAULT_PARAMETER clob, ICON clob, IDENTIFIER varchar2(4000 char) not null, LINK varchar2(4000 char), ONCLICK clob, ONMOUSEOVER clob, SHOW_PARENT_NAME number(1,0), FK_TREE_NODE_PARENT number(10,0), FK_TREE_NODE_TYPE number(10,0), VISIBILITY_PATH clob, VISIBILITY_RULE clob, primary key (id));
create table TREE_NODE_DICTIONARY (id number(10,0) not null, DISCRIMINATOR varchar2(255 char), I18N_CUSTOM_IDENTIFIER varchar2(4000 char), FK_TREE_NODE number(10,0) not null, primary key (id));
create table TREE_NODE_TYPE (id number(10,0) not null, BEAN_SERVICE_NAME varchar2(255 char), DESCRIPTION varchar2(255 char) not null, ICON varchar2(255 char) not null, IDENTIFIER varchar2(4000 char) not null, METHOD_NAME varchar2(255 char), MODEL_CLASS varchar2(255 char), VALID_CHILDREN varchar2(255 char) not null, VIEW_NAME varchar2(255 char), primary key (id));
create table VIEW_BUILDER (id number(10,0) not null, ALTERNATIVE_IDENTIFIERS varchar2(4000 char), CUSTOM_TITLE_KEY varchar2(4000 char), IDENTIFIER varchar2(4000 char), MANAGED_BY varchar2(255 char), STATE varchar2(4000 char), VERSION_DATE timestamp, VERSION_INFO varchar2(255 char), VIEW_NAME varchar2(4000 char), primary key (id));
create table VIEW_BUILDER_PARAMETER (id number(10,0) not null, NAME varchar2(255 char), VALUE varchar2(4000 char), FK_VIEW_BUILDER number(10,0), primary key (id));
create table VIEW_BUILDER_VALIDATOR (VALIDATOR_TYPE varchar2(31 char) not null, id number(10,0) not null, ORDERING number(10,0), FK_VIEW_BUILDER number(10,0), BEAN_NAME varchar2(255 char), FIELD_NAME varchar2(255 char), VALIDATION_RULES clob, CLASS_NAME varchar2(255 char), primary key (id));
create table VIEW_BUILDER_WIDGET_LINK (id number(10,0) not null, LAYOUT_MODE varchar2(255 char), ORDERING number(10,0), FK_VIEW_BUILDER number(10,0), FK_WIDGET number(10,0), primary key (id));
create table WIDGET (DISCRIMINATOR varchar2(31 char) not null, id number(10,0) not null, ATTACCHED_RESOURCE varchar2(4000 char), MODEL_ATTRIBUTE_NAME varchar2(4000 char), NAME varchar2(4000 char), PAGE_ATTRIBUTE_NAME varchar2(255 char), FK_WIDGET number(10,0), SECTION varchar2(255 char), POPULATION_TYPE varchar2(255 char), POPULATION_VALUE varchar2(4000 char), primary key (id));
create table WIDGET_DICTIONARY (id number(10,0) not null, ACTIVATION_DATE date, DEACTIVATION_DATE date, DECORATOR_CLASS varchar2(255 char), DISCRIMINATOR varchar2(255 char), HIDDEN_VALUE varchar2(4000 char), I18N_CUSTOM_IDENTIFIER varchar2(4000 char), ORDERING number(10,0), FK_DICTIONARY number(10,0), STYLE_VALUE varchar2(255 char), FK_WIDGET number(10,0) not null, WITH_CLAUSE varchar2(255 char), primary key (id));
create table WIDGET_LINK (id number(10,0) not null, FK_CHILD number(10,0), ORDERING number(10,0), FK_PARENT number(10,0), primary key (id));
create table WIDGET_PARAMETER (id number(10,0) not null, DISCRIMINATOR varchar2(1000 char), ORDERING number(10,0), VALUE varchar2(1000 char), FK_WIDGET number(10,0), primary key (id));
alter table CONFIGURATION_DATA add constraint UK_p3dd2j9o6k61ky2d53jpgsowh unique (FK_CONFIGURATION_VALUE);
alter table TREE_NODE add constraint UK_efajpbgvwc4kx1lxmcnygrl23 unique (IDENTIFIER);
alter table TREE_NODE_TYPE add constraint UK_mf6kxbiwxb7f0wewifmnvcp0p unique (IDENTIFIER);
alter table AUTHORITIES add constraint FK_2hiekwvkh63suypw2twy1begf foreign key (FK_AUTHORITY) references AUTHORITY;
alter table AUTHORITIES add constraint FK_j8e6xh0qaf39qdnwbeg6poydx foreign key (FK_IDENTITY) references IDENTITY;
alter table AUTHORITIES add constraint FK_aeawwv39ghkjg38ler3apuw8y foreign key (FK_RESOURCE) references RESOURCE_GA;
alter table AUTHORITIES_INFO add constraint FK_17pbbksogqpfq6y8p272vyyvy foreign key (FK_AUTHORITIES) references AUTHORITIES;
alter table AUTHORITIES_INFO add constraint FK_cyj5tvmo34rktn46hld4tw8x8 foreign key (FK_AUTHORITIES_INFO) references AUTHORITIES;
alter table AUTHORITIES_INFO add constraint FK_cyj5tvmo34rktn46hld4tw8x8 foreign key (FK_AUTHORITIES_INFO) references AUTHORITIES_INFO;
alter table CONFIGURATION_DATA add constraint FK_c2au3fg8hx9dsl9gp0vfvtdy foreign key (FK_CONFIGURATION) references CONFIGURATION;
alter table CONFIGURATION_DATA add constraint FK_p3dd2j9o6k61ky2d53jpgsowh foreign key (FK_CONFIGURATION_VALUE) references CONFIGURATION;
alter table CONFIGURATION_LINK add constraint FK_6ocu9oxie3wjfnuxrnocpr8oa foreign key (FK_CHILD) references CONFIGURATION;
alter table CONFIGURATION_LINK add constraint FK_dvoyemamv45ioecyqrxy9sacl foreign key (FK_PARENT) references CONFIGURATION;
alter table I18N_DATA add constraint FK_4bvmtk6yq1wc3vk4aje6j7ntv foreign key (FK_I18N) references I18N;
alter table RESOURCE_GA_LINK add constraint FK_s71dy277ggl662dkbh5gquhol foreign key (FK_CHILD) references RESOURCE_GA;
alter table RESOURCE_GA_LINK add constraint FK_ctc2a2cn86mqtuyroh4ctey0o foreign key (FK_PARENT) references RESOURCE_GA;
alter table SEARCH_BUILDER_PARAMETER add constraint FK_b9nw9p5qvv6b90r80ejk68ej8 foreign key (FK_SEARCH_BUILDER) references SEARCH_BUILDER;
alter table SEARCH_BUILDER_WIDGET_LINK add constraint FK_pgw5oohod4nwrk1gj45ixaxl4 foreign key (FK_SEARCH_BUILDER) references SEARCH_BUILDER;
alter table SEARCH_BUILDER_WIDGET_LINK add constraint FK_b05t6uy4pk5n89p3vw2w2tsjc foreign key (FK_WIDGET) references WIDGET;
alter table TREE_NODE add constraint FK_28fx7qr67i1e18869885kgc4q foreign key (FK_TREE_NODE_PARENT) references TREE_NODE;
alter table TREE_NODE add constraint FK_ohlydp4227pvl9fy430b7ko3u foreign key (FK_TREE_NODE_TYPE) references TREE_NODE_TYPE;
alter table TREE_NODE_DICTIONARY add constraint FK_hbw1waf6fhxosyg3krwg96bym foreign key (FK_TREE_NODE) references TREE_NODE;
alter table VIEW_BUILDER_PARAMETER add constraint FK_l4vh96j0wv1bd97y7648rbbso foreign key (FK_VIEW_BUILDER) references VIEW_BUILDER;
alter table VIEW_BUILDER_VALIDATOR add constraint FK_b4qm4t082qq5xdpnx2l7xcxvi foreign key (FK_VIEW_BUILDER) references VIEW_BUILDER;
alter table VIEW_BUILDER_WIDGET_LINK add constraint FK_9cmyg97fl51la7m6tajc3lfjn foreign key (FK_VIEW_BUILDER) references VIEW_BUILDER;
alter table VIEW_BUILDER_WIDGET_LINK add constraint FK_nlqyjgbf8ucrbpiioqgtuwwv6 foreign key (FK_WIDGET) references WIDGET;
alter table WIDGET add constraint FK_530smuyqgxeyd2xwp86fc0uh1 foreign key (FK_WIDGET) references WIDGET;
alter table WIDGET_DICTIONARY add constraint FK_kkvloaqvdgnbqxcw04xdh9mfy foreign key (FK_DICTIONARY) references WIDGET_DICTIONARY;
alter table WIDGET_DICTIONARY add constraint FK_5ouw34mu4pvsngro5tecbfbrk foreign key (FK_WIDGET) references WIDGET;
alter table WIDGET_LINK add constraint FK_8hilkpgyarn4mwe6v6olv0brn foreign key (FK_CHILD) references WIDGET;
alter table WIDGET_LINK add constraint FK_2dh9nxa6sdjt8xg1iu9ho6pvj foreign key (FK_PARENT) references WIDGET;
alter table WIDGET_PARAMETER add constraint FK_i5vvr94597qrm2p9p5im5qvks foreign key (FK_WIDGET) references WIDGET;
create sequence AUTHORITIES_INFO_SEQ;
create sequence AUTHORITIES_SEQ;
create sequence AUTHORITY_SEQ;
create sequence CONFIGURATION_LINK_SEQ;
create sequence CONFIGURATION_SEQ;
create sequence I18N_SEQ;
create sequence IDENTITY_SEQ;
create sequence RESOURCE_SEQ;
create sequence SEARCH_BUILDER_PARAMETER_SEQ;
create sequence SEARCH_BUILDER_SEQ;
create sequence SEARCH_BUILDER_WIDGET_LINK_SEQ;
create sequence TREE_NODE_DICTIONARY_SEQ;
create sequence TREE_NODE_SEQ;
create sequence TREE_NODE_TYPE_SEQ;
create sequence VIEW_BUILDER_PARAMETER_SEQ;
create sequence VIEW_BUILDER_SEQ;
create sequence VIEW_BUILDER_VALIDATOR_SEQ;
create sequence VIEW_BUILDER_WIDGET_LINK_SEQ;
create sequence WIDGET_DICTIONARY_SEQ;
create sequence WIDGET_LINK_SEQ;
create sequence WIDGET_PARAMETER_SEQ;
create sequence WIDGET_SEQ;